City-Bureau/city-scrapers-fresno

- city_scrapers/spiders/fresno_planning_commission.py
- tests/files/fresno_planning_commission.html
- tests/test_fresno_planning_commission.py
> Fresno planning

- city_scrapers/spiders/madera_co_board_of_supervisors.py
- tests/files/madera_co_board_of_supervisors.html
- tests/test_madera_co_board_of_supervisors.py
> Madera Board of Supervisors

- city_scrapers/spiders/clovis_planning.py
- tests/files/clovis_planning.html
- tests/test_clovis_planning.py
> Madera bos

- city_scrapers/spiders/clovis_city_council.py
- city_scrapers/spiders/porterville_city_council.py
- city_scrapers/spiders/san_joaquin_valley_air_pollution.py
> enforce code style

- city_scrapers/spiders/fre_kingsburg_city_council.py
- tests/files/fre_kingsburg_city_council.html
- tests/test_fre_kingsburg_city_council.py
@jpt-c 
ready to merge
**Issue:** #0016
> #0016 add spider

- city_scrapers/spiders/fre_hanford_city_council.py
- tests/files/fre_hanford_city_council.html
- tests/test_fre_hanford_city_council.py
@jpt-c 
fastest spider yet. 
all files on this PR (spider, html page, unit test) are ready to merge.  
**Issue:** #0040
> #0040 add spider

- city_scrapers/spiders/fre_selma_city_council.py
- tests/files/fre_selma_city_council.html
- tests/test_fre_selma_city_council.py
@jpt-c 
d-o-n-e, done
**Issue:** #0014
> #0014 add spider

- city_scrapers/spiders/fre_kings_bos.py
- tests/files/fre_kings_bos.html
- tests/test_fre_kings_bos.py
@jpt-c 
done. 
**Issue:** #0039
> #0039 add spider

- city_scrapers/spiders/fre_parlier_city_council.py
- tests/files/fre_parlier_city_council.html
- tests/test_fre_parlier_city_council.py
> #0017 add spider

- city_scrapers/spiders/fre_kerman_city_council.py
- tests/files/fre_kerman.html
- tests/test_fre_kerman_city_council.py
@jpt-c 
getting 'HTTP Error 406: Not Acceptable' error in response to using the pdfminer function in def _parse_start (lines#63 - 97)
> #0015 getting 406 error

- city_scrapers/spiders/fre_orange_cove_city_council.py
- tests/files/fre_orange_cove_city_council.html
- tests/test_fre_orange_cove_city_council.py
d-o-n-e, done.
**Issue:** #0019
> #0019 add spider

- city_scrapers/spiders/fre_measure_c_committee.py
- tests/files/fre_measure_c_committee.html
- tests/test_fre_measure_c_committee.py
done. @jpt-c 
**Issue:** #0060
> #0060 add spider

- city_scrapers/spiders/fre_exeter_city_council.py
- tests/files/fre_exeter_city_council.html
- tests/test_fre_exeter_city_council.py
@jpt-c just one of those super productive days. done. 
**Issue:** #0035
> #0035 add spider

- city_scrapers/spiders/fre_reedley_city_council.py
- tests/files/fre_reedley_city_council.html
- tests/test_fre_reedley_city_council.py
@jamesturk 
remember when i forced you to do Kerman City Council for me so I would have an example of requests.get() that I could reference? alas my good sir, it was not all in vain, for i had to use that function on this scraper and i was able to complete it. thanks for always helping me.  
**Issue:** #0013
> #0013 add spider

- city_scrapers/spiders/fre_farmersville_city_council.py
- tests/files/fre_farmersville_city_council.html
- tests/test_fre_farmersville_city_council.py
done. @jpt-c 
**Issue:** #0033
> #0033 add spider

- city_scrapers/spiders/fre_san_joaquin_city_council.py
- tests/files/fre_san_joaquin_city_council.html
- tests/test_fre_san_joaquin_city_council.py
@jpt-c another one bites the dust. 
(so the sad part of this is throughout the project i've been putting off the really hard spiders, and i think its reached a tipping point where there are now only hard spiders left, this was the last easy spider, hashtag sad face.)
**Issue:** #0021
> #0021 add spider

- city_scrapers/spiders/fre_mendota_city_council.py
- tests/files/fre_mendota_city_council.html
- tests/test_fre_mendota_city_council.py
> Mendota #18

- city_scrapers/spiders/fre_madera_irrigation_district.py
- tests/files/fre_madera_irrigation_district.html
- tests/test_fre_madera_irrigation_district.py
@jpt-c you're gonna be so proud, fancy fancy footwork happening in this one and i was able to do it on my own. done.
**Issue:** #0047
> #0047 add spider

- city_scrapers/spiders/friant_water_authority.py
- tests/files/friant_water_authority.html
- tests/test_friant_water_authority.py
**Issue:** #44 
Here is my pull request for the Friant Water Authority spider. Originally, the source was listed as the [calendar](https://friantwater.org/calendar), but since the calendar itself is populated via javascript, I found it was much easier to parse the [meeting events page](https://friantwater.org/meetings-events) instead.
> #0044 spider friant water authority

- city_scrapers/spiders/fre_legislative.py
@jpt-c correct me if i'm wrong, i believe the Fresno City Council meetings of issue#8 are included in this Fresno legistar calendar (https://fresno.legistar.com/Calendar.aspx)? if so, i added one line to the scraper that's already scraping the legistar calendar to also filter for Fresno City Council meetings.
**Issue:** #0008
Include any questions you have about what …
> #0008 add spider (edit fre_legislative.py)

- city_scrapers/spiders/fre_lindsay_city_council.py
- tests/files/fre_lindsay_city_council.html
- tests/test_fre_lindsay_city_council.py
@jpt-c as promised, (1) spider to end the week. we should be down to (7) issues now. i never want to make another scraper ever again.  
**Issue:** #0037
> #0037 add spider

- city_scrapers/spiders/fre_dinuba_city_council.py
- city_scrapers/spiders/fre_exeter_city_council.py
- city_scrapers/spiders/fre_farmersville_city_council.py
- city_scrapers/spiders/fre_lindsay_city_council.py
- city_scrapers/spiders/fre_madera_irrigation_district.py
- city_scrapers/spiders/fre_measure_c_committee.py
- city_scrapers/spiders/fre_mendota_city_council.py
- city_scrapers/spiders/fre_reedley_city_council.py
- city_scrapers/spiders/fre_san_joaquin_city_council.py
> fix timezones

- tests/test_porterville_city_council.py
Fixes the formatting for an import line.
Ensures CI formatting checks pass
> Fix import formatting

- .gitignore
- city_scrapers/spiders/fre_mendota_city_council.py
- tests/files/fre_mendota_city_council.html
- tests/test_fre_mendota_city_council.py
Fixes our Mendota City Council spider (aka. `fre_mendota_city_council`). Also refactors PDF handling.
This spider broke because of a URL change by the agency.
After installing the project using `pipenv`:
1. Activate the virtual environment:
```
pipenv shell
```
2. Run the spider:
```
scrapy crawl fre_mendota_city_council -O test_output.csv
```
3. Monitor the stdout and ensure that the crawl proceeds without raising any errors. Pay attention to the final status report from scrapy.
4. Inspect `test_output.csv` to ensure the data looks valid. I suggest opening a few of the URLs under the source column of test_output.csv and comparing the data for the row with what you see on the page.
> 🕷️ Fix spider: Mendota City Council

- tests/files/fre_fowler_city_council.html
- tests/test_fre_fowler_city_council.py
Fixes the test for Fowler City Council spider (aka. `fre_fowler_city_council`).
The testing suite was failing.
> 🕷️ Fix spider: Fowler City Council

- city_scrapers/spiders/fre_san_joaquin_river_conservancy.py
Reverts City-Bureau/city-scrapers-fresno#136, which didn't delete all the files related to this spider.
> Revert "🗑️ Deprecate spider: San Joaquin River Conservancy"
